### ISSUE TITLE
Default endpoint changed causing etcd3gw.exceptions.Etcd3Exception: Not Found

### ISSUE THREAD

**Issue by yoctozepto** [dims/etcd3-gateway#41]
In the new release (0.2.6 from Jul 30, 2020) etcd3gw ~~is unable to raise (some?) of its own exceptions~~ (the exception wording was mostly unfortunate and I guess we all fell in this trap)
(the truth is:) switched from /v3alpha to /v3beta endpoints which are not available on default etcd installations on current platforms (Ubuntu Bionic, Focal; CentOS 8):

Example:

```
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service [-] Error starting thread.: etcd3gw.exceptions.Etcd3Exception: Not Found
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service Traceback (most recent call last):
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/oslo_service/service.py", line 807, in run_service
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     service.start()
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/cinder/service.py", line 220, in start
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     coordination.COORDINATOR.start()
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/cinder/coordination.py", line 67, in start
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     self.coordinator.start(start_heart=True)
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/tooz/coordination.py", line 689, in start
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     super(CoordinationDriverWithExecutor, self).start(start_heart)
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/tooz/coordination.py", line 426, in start
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     self._start()
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/tooz/drivers/etcd3gw.py", line 224, in _start
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     self._membership_lease = self.client.lease(self.membership_timeout)
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/etcd3gw/client.py", line 122, in lease
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     json={"TTL": ttl, "ID": 0})
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service   File "/var/lib/kolla/venv/lib/python3.6/site-packages/etcd3gw/client.py", line 91, in post
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service     raise exceptions.Etcd3Exception(resp.text, resp.reason)
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service etcd3gw.exceptions.Etcd3Exception: Not Found
2020-08-12 10:22:39.645 1787 ERROR oslo_service.service 
```

**Comment by dims** [comment]
@yoctozepto do you mind submitting a fix that works for you?

**Comment by neiljerram** [comment]
@dims Do you understand the problem here?  I'm afraid I don't see how `etcd3gw.exceptions.Etcd3Exception` can be not found.

**Comment by dims** [comment]
@neiljerram y me as well, hence asking :)

**Comment by yoctozepto** [comment]
I did not analyse it further, just that 0.2.5 works and 0.2.6 does not in the exact same environment. :-)
Both Ubuntu (Bionic, Focal) and CentOS 8 are affected, with their default Pythons.

**Comment by yoctozepto** [comment]
Haha, 🤦 I felt like this error message had a bit weird wording. It's obviously not Etcd3Exception that is missing but that it is HTTP Error 404 "Not Found" being reported in this unfriendly exception. :-)

https://github.com/dims/etcd3-gateway/commit/20b4fca3640bb77b957cc57aef0d114e547e593b had a side effect of switching from /v3alpha to /v3beta endpoints which are available from etcd 3.3 and all current platforms obviously use etcd 3.2. Heh. :-)

I guess the way to go is to restore the previous default to avoid annoying any existing clients. WDYT?

**Comment by yoctozepto** [comment]
Future-wise, tooz needs to be able to differentiate between etcd versions. Now it's impossible to set a different version (and hence endpoint).

**Comment by neiljerram** [comment]
@yoctozepto I was just reaching the same conclusion, i.e. a combination of

1. The /v3beta URL path change.

2. In the OpenStack environment, for some reason the 'exceptions.Etcd3Exception' import does not work and has never worked, but the environment has only just hit a condition where it wants to raise an exception, because of (1).

IME, the usual reason for imports weirdly not working is monkey-patching connected with eventlet, urllib3 or requests...

**Comment by yoctozepto** [comment]
@neiljerram Nah, it's working. We fell for the wording - the "Not Found" is for the HTTP response body, not Python message.

**Comment by neiljerram** [comment]
> @neiljerram Nah, it's working. We fell for the wording - the "Not Found" is for the HTTP response body, not Python message.

Ah, good one! :smile:

**Comment by yoctozepto** [comment]
Anyway, this one is fixed by above. The other issue is this wording - the message is unhelpful and, in fact, misleading (tricked more than one person). :-)

**Comment by neiljerram** [comment]
@yoctozepto There is an `api_path` arg to the `Etcd3Client` constructor.  Did you consider setting that in the calling code, instead of #44 ?

**Comment by yoctozepto** [comment]
@neiljerram Yeah, it would work but I guess the defaults shouldn't change if etcd3gw is not bumping major. Also, considering the majority of stable users would be still sitting on 3.2...

The client is tooz which would need to learn to allow users to choose the version. I mentioned it above.

**Comment by yoctozepto** [comment]
Reworded: let current users benefit from fixes and not bind them to change their current interfaces.

**Comment by neiljerram** [comment]
Well it's OK with me to revert the default to v3alpha; not sure about reverting the whole change.  I will comment on the PR.

Then it would be great if someone could add autodetection of v3alpha vs v3beta vs v3, since the etcd team seem so keen on changing this!

**Comment by neiljerram** [comment]
> not sure about reverting the whole change

Apologies, I misread the change about an hour ago.  I see that you aren't "reverting the whole change".
