### ISSUE TITLE
Having IPv6 addresses in client URL fails

### ISSUE THREAD

**Issue by jharbott** [dims/etcd3-gateway#9]
See https://review.openstack.org/505168 for context, config file has:

```[coordination]
backend_url = etcd3+http://[::1]:2379
```

but it seems to get messed up along the way 

```
Sep 19 15:14:36.951835 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server [None req-bf45693c-0d1e-4e1f-884b-e1a5419b1a81 tempest-TestVolumeSwap-1355161147 None] Exception during message handling: InvalidURL: Failed to parse: ::1:2379
Sep 19 15:14:36.951988 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server Traceback (most recent call last):
Sep 19 15:14:36.952169 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/server.py", line 160, in _process_incoming
Sep 19 15:14:36.952324 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
Sep 19 15:14:36.952500 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 222, in dispatch
Sep 19 15:14:36.952662 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
Sep 19 15:14:36.952804 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 192, in _do_dispatch
Sep 19 15:14:36.952954 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
Sep 19 15:14:36.953153 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "<decorator-gen-245>", line 2, in attach_volume
Sep 19 15:14:36.953305 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/opt/stack/new/cinder/cinder/coordination.py", line 169, in _synchronized
Sep 19 15:14:36.953439 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     with lock(blocking):
Sep 19 15:14:36.954766 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tooz/locking.py", line 31, in __enter__
Sep 19 15:14:36.954949 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return self.lock.__enter__(*self.args, **self.kwargs)
Sep 19 15:14:36.955110 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tooz/locking.py", line 52, in __enter__
Sep 19 15:14:36.955404 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     acquired = self.acquire(*args, **kwargs)
Sep 19 15:14:36.955559 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tooz/drivers/etcd3gw.py", line 38, in wrapper
Sep 19 15:14:36.955711 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return func(*args, **kwargs)
Sep 19 15:14:36.958234 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tooz/drivers/etcd3gw.py", line 113, in acquire
Sep 19 15:14:36.958396 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return _acquire()
Sep 19 15:14:36.958541 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tenacity/__init__.py", line 171, in wrapped_f
Sep 19 15:14:36.958690 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return self.call(f, *args, **kw)
Sep 19 15:14:36.958850 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tenacity/__init__.py", line 248, in call
Sep 19 15:14:36.959000 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     start_time=start_time)
Sep 19 15:14:36.959157 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tenacity/__init__.py", line 203, in iter
Sep 19 15:14:36.959309 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return fut.result()
Sep 19 15:14:36.959461 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 422, in result
Sep 19 15:14:36.959612 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return self.__get_result()
Sep 19 15:14:36.959755 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tenacity/__init__.py", line 251, in call
Sep 19 15:14:36.959902 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     result = fn(*args, **kwargs)
Sep 19 15:14:36.960044 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/tooz/drivers/etcd3gw.py", line 82, in _acquire
Sep 19 15:14:36.960185 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     self._lease = self._coord.client.lease(self._timeout)
Sep 19 15:14:36.960332 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/etcd3gw/client.py", line 113, in lease
Sep 19 15:14:36.960520 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     json={"TTL": ttl, "ID": 0})
Sep 19 15:14:36.960665 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/etcd3gw/client.py", line 78, in post
Sep 19 15:14:36.960823 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     resp = self.session.post(*args, **kwargs)
Sep 19 15:14:36.960977 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
Sep 19 15:14:36.961162 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     return self.request('POST', url, data=data, json=json, **kwargs)
Sep 19 15:14:36.961305 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 494, in request
Sep 19 15:14:36.961448 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     prep = self.prepare_request(req)
Sep 19 15:14:36.961607 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 437, in prepare_request
Sep 19 15:14:36.961757 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     hooks=merge_hooks(request.hooks, self.hooks),
Sep 19 15:14:36.961899 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 305, in prepare
Sep 19 15:14:36.962069 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     self.prepare_url(url, params)
Sep 19 15:14:36.962212 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 373, in prepare_url
Sep 19 15:14:36.962354 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server     raise InvalidURL(*e.args)
Sep 19 15:14:36.962495 ubuntu-xenial-infracloud-chocolate-10994920 cinder-volume[22504]: ERROR oslo_messaging.rpc.server InvalidURL: Failed to parse: ::1:2379

```

**Comment by dims** [comment]
Thanks @jharbott fixed! will cut a release a bit later this week
